name: Deploy React Counter App

on:
  push:
    branches:
      - main
    paths:
      - "packages/react-counter/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: => Checkout repo
        uses: actions/checkout@v4

      - name: => Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: => Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: => Build Docker image (from root!)
        run: |
          docker build \
          -f packages/react-counter/Dockerfile \
          -t ${{ secrets.DOCKER_USERNAME }}/react-counter:latest .

      - name: => Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/react-counter:latest

      - name: => Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ vars.HOST }}
          port: ${{ vars.PORT }}
          username: ${{ secrets.APP_HOSTER_USER }}
          key: ${{ secrets.APP_HOSTER_SSH }}
          script: |
            # -------------------------
            # Stop and remove old container if exists
            # -------------------------
            docker stop react-counter || true
            docker rm react-counter || true

            # -------------------------
            # Pull latest image
            # -------------------------
            docker pull ${{ secrets.DOCKER_USERNAME }}/react-counter:latest

            # -------------------------
            # Run container
            # -------------------------
            docker run -d \
              --name react-counter \
              --restart=always \
              -p 8080:80 \
              ${{ secrets.DOCKER_USERNAME }}/react-counter:latest
