name: Deploy React Counter App

on:
  push:
    paths:
      - "packages/react-counter/**"
      - "nginx/app-hoster.conf"
      - "packages/react-counter/description.json"
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: => Checkout repo
        uses: actions/checkout@v4

      - name: => Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: => Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: => Build Docker image
        working-directory: packages/react-counter
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/react-counter:latest .

      - name: => Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/react-counter:latest

      - name: => Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ vars.HOST }}
          port: ${{ vars.PORT }}
          username: ${{ secrets.APP_HOSTER_USER }}
          key: ${{ secrets.APP_HOSTER_SSH }}
          script: |
            # -------------------------
            # Stop and remove old container if exists
            # -------------------------
            docker stop react-counter || true
            docker rm react-counter || true

            # -------------------------
            # Cleanup old images
            # -------------------------
            docker image prune -f || true

            # -------------------------
            # Pull latest image
            # -------------------------
            docker pull ${{ secrets.DOCKER_USERNAME }}/react-counter:latest

            # -------------------------
            # Run container
            # -------------------------
            docker run -d \
              --name react-counter \
              --network hoster-net \
              --restart=always \
              -p 8080:80 \
              ${{ secrets.DOCKER_USERNAME }}/react-counter:latest

            # -------------------------
            # Update Nginx config
            # -------------------------
            cp ~/app-hoster.conf /etc/nginx/sites-available/hoster-apps.conf
            ln -sf /etc/nginx/sites-available/hoster-apps.conf /etc/nginx/sites-enabled/hoster-apps.conf

            # -------------------------
            # Test config and reload Nginx
            # -------------------------
            nginx -t && systemctl reload nginx